name: Deploy VuePress to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的分支，根据你的实际情况修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行器

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 指定 Node.js 版本，根据 VuePress 要求配置

    - name: Install dependencies
      run: npm install

    - name: Build VuePress site
      run: npm run build
      working-directory: docs  # 假设你的 VuePress 站点在 docs 目录下

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vuepress/dist  # VuePress 构建输出目录
